resources:
# Automation scripts repo
  - name: cd_war_vm_repo
    type: gitRepo
    integration: "drship_github"
    versionTemplate:
      sourceName: "devops-recipes/cd_war_vm_ansible"
      branch: master

# AWS PEM Key
  - name: cd_war_vm_pem
    type: integration
    integration: "drship_aws_pem"

# Nexus endpoint
  - name: cd_nexus_src
    type: integration
    integration: "drship_nexus"

# AWS CLI config
  - name: aws_cli_vm
    type: cliConfig
    integration: "drship_aws"
    pointer:
      region: us-east-1

jobs:
# Provision AWS VPC with Ansible
  - name: deploy_war_vm_ans
    type: runSh
    steps:
      - IN: war_loc
      - IN: cd_war_vm_repo
        switch: off
      - IN: aws_cli_vm
        switch: off
      - IN: aws_ec2_info
        switch: off
      - IN: cd_war_vm_pem
        switch: off
      - TASK:
          name: deploy_war
          runtime:
            options:
              imageName: "devopsrecipes/build_custom_ci"
              imageTag: "582227"
              pull: true
              env:
                - AWS_REGION:         "us-east-1"
                - artifact_dest:      "/tmp/jar"
          script:
            - pushd $(shipctl get_resource_state "cd_war_vm_repo")/ansible
            - export artifact_filename=$artifact_id"-"$artifact_version"."$artifact_extension
            - shipctl replace group_vars/variables.yml
            - ansible-playbook -v war_deploy.yml
            - popd
    flags:
      - cd
      - vm
      - aws
      - ansible
      - war
