---

# roles/war_deploy/tasks/main.yml

- name: Make temp dir
  shell: "mkdir -p {{ artifact_dest }}"

- name: Copy JAR file
  copy:
    src: "{{ artifact_filename }}"
    dest: "{{ artifact_dest }}/."

- name: Test copy action
  shell: "ls {{ artifact_dest }}"
