---

# roles/war_fetch/tasks/main.yml

- name:                 Download artifact from Maven
  maven_artifact:
    repository_url:     "{{ repository_url }}"
    group_id:           "{{ group_id }}"
    artifact_id:        "{{ artifact_id }}"
    version:            "{{ artifact_version }}"
    extension:          "{{ artifact_extension }}"
    dest:               "{{ artifact_filename }}"
